version: 2.1
jobs:
  py-test:
    docker:
      # does not build on python3.8
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: make ci-test
  node-test:
    docker:
      - image: cimg/node:12.18
    environment:
      IS_DEPLOYABLE: false
    working_directory: ~/project/amundsen_application/explore/static/
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run test

workflows:
  test-workflow:
    jobs:
      - py-test
      - node-test
